name: Enforce code style standards

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run linter
      run: |
        docker run --rm -v $(pwd):/app php-cs-fixer fix src/ --rules=@PSR12 --using-cache=no
        docker run --rm -v $(pwd):/app php-cs-fixer fix tests/ --rules=@PSR12 --using-cache=no

    - name: Commit and push VERSION file
      if: ${{ steps.linter.outputs.changed == 'true' }} # Only commit if files are modified
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add $(git diff --name-only --cached)
        git commit -m "ci: linter"
        git push

