name: Enforce code style standards

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build linter image
      run: |
        docker build -t php-cs-fixer:ci -f Dockerfile-php-style .

    - name: Run linter
      run: |
        docker run --rm -v $(pwd):/app php-cs-fixer:ci fix src/ --rules=@PSR12 --using-cache=no
        docker run --rm -v $(pwd):/app php-cs-fixer:ci fix tests/ --rules=@PSR12 --using-cache=no

    - name: Commit and push
      run: |
        if [[ $(git diff --name-only) ]]; then
          echo "Changes detected. Committing and pushing..."
          git diff --name-only
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add $(git diff --name-only --cached)
          git commit -m "ci: linter"
          git push
        else
          echo "No changes detected. Skipping commit."
        fi

