name: Unit tests

on:
  workflow_dispatch:
  push:
#    branches:
#      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.7
#        options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Compose
      uses: docker/setup-buildx-action@v2
      with:
        version: latest

    - name: Run Docker Compose Up and Build
      run: |
        docker compose up --build

